# Generated by Django 6.0 on 2025-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
